export const MARQUES = [
    {marqueLibelle: "ALEKO"},
    {marqueLibelle: "ALFA ROMEO"},
    {marqueLibelle: "ALPINA"},
    {marqueLibelle: "ALPINE RENAULT"},
    {marqueLibelle: "ARO"},
    {marqueLibelle: "ASIA"},
    {marqueLibelle: "ASTON MARTIN"},
    {marqueLibelle: "AUDI"},
    {marqueLibelle: "AUSTIN"},
    {marqueLibelle: "AUTOBIANCHI"},
    {marqueLibelle: "AUVERLAND"},
    {marqueLibelle: "BEDFORD"},
    {marqueLibelle: "BEE BEE AUTOMOTIVE"},
    {marqueLibelle: "BENTLEY"},
    {marqueLibelle: "BERTONE"},
    {marqueLibelle: "BMW"},
    {marqueLibelle: "BUICK"},
    {marqueLibelle: "CADILLAC"},
    {marqueLibelle: "CATERHAM"},
    {marqueLibelle: "CHEVROLET"},
    {marqueLibelle: "CHRYSLER"},
    {marqueLibelle: "CITROEN"},
    {marqueLibelle: "COURB"},
    {marqueLibelle: "DACIA"},
    {marqueLibelle: "DAEWOO"},
    {marqueLibelle: "DAF"},
    {marqueLibelle: "DAIHATSU"},
    {marqueLibelle: "DAIMLER"},
    {marqueLibelle: "DATSUN"},
    {marqueLibelle: "DODGE"},
    {marqueLibelle: "DS"},
    {marqueLibelle: "EBRO"},
    {marqueLibelle: "FERRARI"},
    {marqueLibelle: "FIAT"},
    {marqueLibelle: "FORD"},
    {marqueLibelle: "FISKER"},
    {marqueLibelle: "FSO-POLSKI"},
    {marqueLibelle: "GAC GONOW"},
    {marqueLibelle: "GME"},
    {marqueLibelle: "GRANDIN"},
    {marqueLibelle: "HONDA"},
    {marqueLibelle: "HUMMER"},
    {marqueLibelle: "HYUNDAI"},
    {marqueLibelle: "INFINITI"},
    {marqueLibelle: "INNOCENTI"},
    {marqueLibelle: "ISUZU"},
    {marqueLibelle: "IVECO"},
    {marqueLibelle: "JAGUAR"},
    {marqueLibelle: "JEEP"},
    {marqueLibelle: "KIA"},
    {marqueLibelle: "LADA"},
    {marqueLibelle: "LAMBORGHINI"},
    {marqueLibelle: "LANCIA"},
    {marqueLibelle: "LAND ROVER"},
    {marqueLibelle: "LDV"},
    {marqueLibelle: "LEXUS"},
    {marqueLibelle: "LOTUS"},
    {marqueLibelle: "MAHINDRA"},
    {marqueLibelle: "MAN"},
    {marqueLibelle: "MARUTI"},
    {marqueLibelle: "MASERATI"},
    {marqueLibelle: "MATRA"},
    {marqueLibelle: "MAZDA"},
    {marqueLibelle: "MCC"},
    {marqueLibelle: "MC LAREN"},
    {marqueLibelle: "MEGA"},
    {marqueLibelle: "MERCEDES"},
    {marqueLibelle: "MG"},
    {marqueLibelle: "MIA"},
    {marqueLibelle: "MINI"},
    {marqueLibelle: "MITSUBISHI"},
    {marqueLibelle: "MORGAN"},
    {marqueLibelle: "MPM MOTORS"},
    {marqueLibelle: "NISSAN"},
    {marqueLibelle: "OPEL"},
    {marqueLibelle: "PANHARD"},
    {marqueLibelle: "PEUGEOT"},
    {marqueLibelle: "PIAGGIO"},
    {marqueLibelle: "PONTIAC"},
    {marqueLibelle: "PORSCHE"},
    {marqueLibelle: "PROTON"},
    {marqueLibelle: "RENAULT"},
    {marqueLibelle: "ROLLS ROYCE"},
    {marqueLibelle: "ROVER"},
    {marqueLibelle: "SAAB"},
    {marqueLibelle: "SANTANA"},
    {marqueLibelle: "SEAT"},
    {marqueLibelle: "SKODA"},
    {marqueLibelle: "SMART"},
    {marqueLibelle: "SSANGYONG"},
    {marqueLibelle: "SUBARU"},
    {marqueLibelle: "SUNBEAM"},
    {marqueLibelle: "SUZUKI"},
    {marqueLibelle: "TALBOT"},
    {marqueLibelle: "TATA"},
    {marqueLibelle: "TESLA"},
    {marqueLibelle: "THINK"},
    {marqueLibelle: "TOYOTA"},
    {marqueLibelle: "TRIUMPH"},
    {marqueLibelle: "UMM"},
    {marqueLibelle: "VOLKSWAGEN"},
    {marqueLibelle: "VOLVO"},
    {marqueLibelle: "ZASTAVA"},
    {marqueLibelle: "ZAZ"},
];